### PR TITLE
Add section on linters & auto-formatters.

### LINKED ISSUE #18: Add mentions of linters.
In recent years, many if not most open source projects & organizations have adopted tools like `flake8`, `pylint`, `black`, and `isort` to detect & prevent style issues.  (`black` is officially a Python Software Foundation project now, driving a lot more adoption as of late.)

- https://github.com/psf/black
- https://github.com/PyCQA

If there's interest, I'd be glad to write a section on these tools.

### PR DESCRIPTION
**Pull request by jamesturk**
Draft text for introducing students to linters & auto-formatters.

Fixes #18.

### CODE REVIEW

**Review by borjasotomayor — APPROVED** [review]
This looks good to me, but I've also added @ar0r as a reviewer in case she has any thoughts/comments on adding this to the style guide (since she's also relying heavily on this style guide this quarter)

**Review by ar0r — CHANGES_REQUESTED** [review]
Thank you for writing up this section.

I'd like to add the Linters discussion now and hold off on adding auto-formatters until next quarter.  I am not familiar with the auto-formatting tools that are recommended and I would like to have a chance to review them before we add them to the guide.

**Comment by jamesturk** [comment]
👍 Thanks for taking a look, I've removed the section on autoformatters.

**Comment by ar0r** [comment]
These changes look good to me.

**Comment by ar0r** [comment]
Quick question: is there a reason to prefer one of these linters over the others or to use more than one?  We currently use pylint in 141.

**Comment by jamesturk** [comment]
They do check different things & give somewhat different results, I've seen a handful of projects that make use of both.  

I think the quick version is that `pylint` is a bit more comprehensive out of the gate whereas flake8 seems more configurable. It also has a lot of popular plugins that can extend its linting capabilities to cover other patterns people want to check for (https://github.com/DmytroLitvinov/awesome-flake8-extensions) such as leaving debugging statements in code or validating docstrings.

**Pull request merged**
