### PR TITLE
Linux updates

### PR DESCRIPTION
**Pull request by ar0r**
Split Linux tutorial into smaller sections.   Shifted the discussion of pulling the tutorial materials into the introduction.

### CODE REVIEW

**Comment by victor-almaraz** [comment]
I made minor wording changes to the following files.

- `linux-compile-and-run.rst`
- `linux-filesystem.rst`
- `linux-intro.rst`  

There may be a missing exercise in `linux-filesystem.rst`. The exercise 6 references a copy of `test.txt` in the `backups` directory but we have not asked the students to copy the file there. Likewise, I think there is a missing list of shortcuts in lines 43 and 44 of `linux-tip-tricks.rst`.

**Comment by ar0r** [comment]
Victors changes are good.  I addressed the issues raised by Victor: (1) I fixed the reference to the copy of test.txt and (2) I added the missing shortcuts.

**Comment by borjasotomayor** [comment]
I've pushed a few small changes, but this looks overall good to me. That said, I didn't work through the tutorial or proofread it carefully (I just checked that the general structure looked good, that links were working, that nothing looked out of place, etc.), so it might not be a bad idea to find someone (who isn't already involved in the student guide) to work through it in case they spot any issues in any of the steps, etc.

I don't think we have to block on this, though, so I'll go ahead and approve the PR and deploy the changes.

**Comment by borjasotomayor** [comment]
The updated tutorial should now be available at https://uchicago-cs.github.io/student-resource-guide/

**Pull request merged**
