### PR TITLE
Git solo

### PR DESCRIPTION
**Pull request by ar0r**
Replaces the original git basics tutorial with a new version that starts with a local-only repository and introduces a remote repository only after students have learned the basics of creating commits.  This request includes the required distribution files.

### CODE REVIEW

**Comment by borjasotomayor** [comment]
I have pushed a number of updates to the tutorial in [c1e51b8](https://github.com/uchicago-cs/student-resource-guide/pull/27/commits/c1e51b8ed3f578caf2e9bf37ee4875d45c27dd2b). We will eventually need to update screenshots to use the naming convention in the Student Resource Guide but, in the interim, we could get away with a warning box that says the screenshots use "solo" instead of "basics", and that they should ignore that discrepancy.

I also wonder whether it makes sense to spin off everything starting at "Working with a Remote Server" into an "Intermediate Git Tutorial". As it stands, the "Git Basics" tutorial feels very long.

One minor issue I wasn't sure how to address:

> If you want your output to match ours, use the message ``"More salutations"``.

This "More salutations" isn't mentioned again in the tutorial, and presumably refers to some output the reader would compare their output with. Is this leftover from the CS 141 tutorial?

**Comment by ar0r** [comment]
I have updated the tutorial to address all the comments I received from James, except the suggestion to switch to setting the global default branch name to main.  We can make this change once Techstaff updates the Linux machines.

I also addressed Borja's comments.

I think someone who is good at proofreading needs to do a careful proofreading pass.

My reading of the branches tutorial is that the students can use the repo they created for the basic sections of the tutorial or they can create a new one.  I don't think we need to add any extra files to the basic distribution.  Someone should verify this claim.

At some point, we may want to update the branches section to use Python examples rather than C for the sake of consistency.   This change is not essential and should not hold up releasing this version.

**Comment by victor-almaraz** [comment]
I made minor changes to the following files to fix typos or improve clarity:
- `git-intro.rst`
- `git-local.rst`
- `git-prepare-github.rst`
- `git-remote.rst`

I would update the language in lines 33-34 of `git-local.rst` to either clarify who to ask help or remove it altogether. Same for lines 191-192 of `git-prepare-github.rst`.Ω

**Comment by ar0r** [comment]
Victor's changes look good.

**Comment by borjasotomayor** [comment]
The updated tutorial should now be available at https://uchicago-cs.github.io/student-resource-guide/

**Pull request merged**
